# Generated by Django 4.2.3 on 2023-12-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('asus', 'Asus'), ('dell', 'Dell'), ('acer', 'Acer'), ('apple', 'Apple'), ('microsoft', 'Microsoft'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('samsung', 'Samsung'), ('msi', 'MSI'), ('toshiba', 'Toshiba'), ('alienware', 'Alienware'), ('razer', 'Razer'), ('xiaomi', 'Xiaomi'), ('huawei', 'Huawei')], max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('ram_gb', models.PositiveSmallIntegerField()),
                ('storage_type', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD')], max_length=8)),
                ('storage_gb', models.PositiveSmallIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.PositiveIntegerField()),
            ],
        ),
    ]
