# Generated by Django 4.2.3 on 2023-12-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_laptop_created_at_laptop_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Deleted'), (2, 'Banned'), (3, 'Shadowbanned'), (4, 'Not Published'), (5, 'Published')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, choices=[('php', 'Old farts'), ('c++', 'Timeless classics'), ('javascript', 'Street magicians')], max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastSubmission',
            fields=[
            ],
            options={
                'ordering': ['published_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('challenges.submission',),
        ),
    ]
