# Generated by Django 4.2.3 on 2023-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_submission_lastsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastsubmission',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(blank=True, choices=[('php', 'PHP'), ('c++', 'C++'), ('javascript', 'JavaScript')], max_length=128, null=True),
        ),
    ]
