# Generated by Django 4.2.3 on 2023-12-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_lastsubmission_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastSubmission',
        ),
        migrations.CreateModel(
            name='LatestSubmission',
            fields=[
            ],
            options={
                'ordering': ['-published_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('challenges.submission',),
        ),
    ]
