# Generated by Django 4.2.3 on 2023-12-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_delete_lastsubmission_latestsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='manufacturer',
            field=models.CharField(choices=[('asus', 'Asus'), ('dell', 'Dell'), ('acer', 'Acer'), ('apple', 'Apple'), ('ms', 'Microsoft'), ('hp', 'Hewlett-Packard'), ('lenovo', 'Lenovo'), ('samsung', 'Samsung'), ('msi', 'MSI'), ('toshiba', 'Toshiba'), ('alienware', 'AlienWare'), ('razer', 'Razer'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi')], max_length=64),
        ),
    ]
